### PR TITLE
issue-3 support es6 templates

### LINKED ISSUE #3: Support ES6 style templates
As described [here](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html).

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #3

### CODE REVIEW

**Comment by floatdrop** [comment]
Shouldn't it be merged in, like, `beta` branch for now? Does jspm registry allows `jsx@0.13-beta.1` syntax?

**Comment by prayerslayer** [comment]
> Shouldn't it be merged in, like, beta branch for now?

Yes, a `beta` branch is probably a better idea as there could be more `0.12.x` releases of React.

> Does jspm registry allows jsx@0.13-beta.1 syntax?

It better, because this format is specified as a `pre-release` in the [semver spec](http://semver.org/). I did not try, but according to [this regex in the source](https://github.com/jspm/jspm-cli/blob/master/lib/semver.js#L16) it should be fine.

**Comment by floatdrop** [comment]
Sorry for delay - `beta` branch is in, you can use it like this:

`jspm install jsx@beta`

**Comment by prayerslayer** [comment]
Thanks for responding so quickly!

**Pull request closed without merging**
