### PR TITLE
Renamed for npmjs.org

### PR DESCRIPTION
**Pull request by trusktr**
https://www.npmjs.com/package/system-jsx

Added you as owner to the package.

The changes were made against the v0.1.1 commit and published to npm.

### CODE REVIEW

**Comment by floatdrop** [comment]
@trusktr is there any reason to do so? Isn't jspm registry just pointing to this repository (https://github.com/jspm/registry/blob/master/registry.json#L10)

**Comment by trusktr** [comment]
Some are using SystemJS directly, and managing packages with npm. Jspm just adds that package management and configuration layer on top of SystemJS.

**Comment by floatdrop** [comment]
@guybedford any hint on plugins names? There are lots of `plugin-*` in registry and two `system-*` (md and font).

**Comment by guybedford** [comment]
@floatdrop I'm personally not a fan of putting plugins on npm, because that means running the react-tools dependency through npm as well, which doesn't really make sense. Personally I'm not publishing my plugins to npm, although it can make sense for plugins without dependencies I suppose. In these cases probably `system-*`.

**Comment by trusktr** [comment]
I'd say just maximise consumability. It might not fit your needs @guybedford, but it might fit someone else's needs, and there's not really any harm in it other than having to maintain (push code to) the npmjs package.

**Comment by guybedford** [comment]
Thinking further about this the alternative for compatibility would be to write the plugin such that it is a plain npm libraries - that is with no `jspm` in the package.json at all. Then it would be fully installable as an npm package, based on npm conventions, and would make sense to publish to npm. I'm not sure what the benefit of this is though, in comparison to publishing to GitHub, which I personally find a little more flexible.

**Comment by guybedford** [comment]
That is - even SystemJS users that wanted to use the plugin could install it with npm, but then the dependencies wouldn't resolve in SystemJS, so there isn't much benefit.

**Comment by trusktr** [comment]
> dependencies wouldn't resolve

By that you mean that `require(foo/Module)` doesn't work without having to first make the manual config right? I seem to have seen some people in gitter using only npm+systemjs. They must be wiring up their deps by hand like RequireJS users do.

**Comment by guybedford** [comment]
Yes exactly.

**Comment by trusktr** [comment]
Is this manual wiring part of the ES6 Module spec?

**Comment by guybedford** [comment]
The default resolution is just like URLs, then implementations can add their own rules on top of that.

**Comment by trusktr** [comment]
I guess that means paths like `famous/src/core/Surface` would need custom wiring because then they'd be relative to the current module's path. Is SystemJS' map and paths config ability part of the spec?

**Comment by guybedford** [comment]
Exactly, yes they are specific to SystemJS.

**Pull request closed without merging**
